modLoader="lowcodefml"
loaderVersion="*"
issueTrackerURL="https://github.com/OOrreeooss/TinkersDolabrae/issues"
license="MIT"
[[mods]]
    modId="tinkers_dolabrae"
    version="1.0.1"
    displayName="Tinkers' Dolabrae"
    authors="OOrreeooss"
    description='''A thingpack for Tinkers' Construct that adds dolabrae.'''
[[dependencies.tinkers_dolabrae]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.10.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_dolabrae]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0.9.9,)"
    ordering="NONE"
    side="BOTH"
